<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/star-rating.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/star-rating.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body style="padding:0px;background-color:#f3f3f3;">
    
    <div  style="background-color:grey;top:0px;padding:0px;">
    <div class="container" style="padding-top: 10px;">
    <img src="<?php echo $this->basePath()?>/images/zf2-logo.png">
    
    <div class="col-md-4" style="float:right;">
    <form class="form-inline">     
  <input type="email" style="margin-right: 0px;" class="form-control" id="exampleInputEmail2" placeholder="在这里搜索古诗词">
  <button type="submit" class="btn btn-default" style="margin-left:0px;">搜索</button>
  </form>
  </div>
  
    </div>
    </div>
    
    
        <div class="navbar navbar-default navbar-static-top" style="background-color:grey;margin-bottom: 0px;margin-top:0px;">
           	<div class="container" style="background-color:#000;padding:0px;margin-bottom:0px;">
					<div class="navbar-header" style="background-color:#000;padding:0px;">
                 	  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					  </button>
					</div>
				</div>
                    <!--<a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Skeleton Application') ?></a>--->
                <div class="container" style="margin-top: 10px;">
                    <div class="navbar-collapse collapse" style="color:white;margin:0px;padding:0px">
                        <ul class="nav navbar-nav" style="margin-bottom:0px;padding:0px;font-size:20px;">
                            <li style="borer-right:solid 1px black;margin-right:10px;">首页</li>
                            <li style="borer-right:solid 1px black;margin-right:10px;">查询</li>
                            <li style="borer-right:solid 1px black;margin-right:10px;">诗文</li>
                            <li style="borer-right:solid 1px black;margin-right:10px;">名句</li>
                            <li style="borer-right:solid 1px black;margin-right:10px;">典籍</li>
                            <li style="borer-right:solid 1px black;margin-right:10px;">随便看看</li>                                                     
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
							
							<li id="lgin" style="font-size:20px;"> <p onClick="myFunction()">登录</p></li>
					  </ul>
                    </div><!--/.nav-collapse -->
               </div>
        </div>
        <div>
     
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2006 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
