
                    <div style="background-color:#CCC;">
                        <ul class="container" style="padding:10px;list-style-type:none;margin-bottom:0px;background-color:#CCC;postion:absolute;">
                           <?php foreach ($blog as $blogs) : ?>
                           <li style="color:black;margin-right:10px;position:relative;float:left;"><?php echo $this->escapeHtml($blogs->artist);?></li>
                           <?php endforeach; ?>
                        </ul>
                    </div>
<div style="background-color: #f3f3f3;">            
<div class="container">
<div class="col-md-9">
<!-- left block -->
<div style="padding:10px;">
<div style="font-weight: bold;padding:10px;border-bottom:dotted 1px grey;">
<span>杜牧</span>
</div>

<div style="float:left;margin-bottom:20px;padding:10px;">
<div class="col-md-2"><img src="<?php echo $this->basePath()?>/images/wangwei.jpg"></div>
<div class="col-md-10">
<span>
杜牧（公元803－约852年），字牧之，号樊川居士，汉族，京兆万年（今陕西西安）人，唐代诗人。杜牧人称“小杜”，以别于杜甫。与李商隐并称“小李杜”。因晚年居长安南樊川别墅，故后世称“杜樊川”，著有《樊川文集》。
</span>
</div>
</div>

<!-- end of author description -->
<div style="float:left;margin-bottom:20px;padding:10px;border-bottom:dotted 1px grey;">
<div><span>介绍</span></div>
<div><span>杜牧（公元803－约853年），字牧之，号“樊川居士”，号称杜紫薇。京兆万年（今陕西西安）人，晚唐诗人。（来源：中书省别名紫微省，因此人称其为“杜紫薇” ）晚唐时期.唐代文学家，后人称杜甫为“老杜”，称杜牧为“小杜”。《阿(ē)房宫赋》亦颇有名。杰出的诗人、散文家，是宰相杜佑之孙...</span></div>
</div>

<!-- end of 1 block -->
<div style="float:left;margin-bottom:20px;padding:10px;border-bottom:dotted 1px grey;">
<div><span>生平</span></div>
<div><span>杜牧（公元803－约853年），字牧之，号“樊川居士”，号称杜紫薇。京兆万年（今陕西西安）人，晚唐诗人。（来源：中书省别名紫微省，因此人称其为“杜紫薇” ）晚唐时期.唐代文学家，后人称杜甫为“老杜”，称杜牧为“小杜”。《阿(ē)房宫赋》亦颇有名。杰出的诗人、散文家，是宰相杜佑之孙...</span></div>
</div>

<!-- end of 2 block -->
<div style="float:left;margin-bottom:20px;padding:10px;border-bottom:dotted 1px grey;">
<div><span>典故</span></div>
<div><span>杜牧（公元803－约853年），字牧之，号“樊川居士”，号称杜紫薇。京兆万年（今陕西西安）人，晚唐诗人。（来源：中书省别名紫微省，因此人称其为“杜紫薇” ）晚唐时期.唐代文学家，后人称杜甫为“老杜”，称杜牧为“小杜”。《阿(ē)房宫赋》亦颇有名。杰出的诗人、散文家，是宰相杜佑之孙...</span></div>
</div>

<!-- end of 3 block -->
<div style="float:left;margin-bottom:20px;padding:10px;border-bottom:dotted 1px grey;">
<div><span>文学成就</span></div>
<div><span>杜牧（公元803－约853年），字牧之，号“樊川居士”，号称杜紫薇。京兆万年（今陕西西安）人，晚唐诗人。（来源：中书省别名紫微省，因此人称其为“杜紫薇” ）晚唐时期.唐代文学家，后人称杜甫为“老杜”，称杜牧为“小杜”。《阿(ē)房宫赋》亦颇有名。杰出的诗人、散文家，是宰相杜佑之孙...</span></div>
</div>

<!-- end of 4 block -->
<div style="float:left;margin-bottom:20px;padding:10px;border-bottom:dotted 1px grey;">
<div><span>评价</span></div>
<div><span>杜牧（公元803－约853年），字牧之，号“樊川居士”，号称杜紫薇。京兆万年（今陕西西安）人，晚唐诗人。（来源：中书省别名紫微省，因此人称其为“杜紫薇” ）晚唐时期.唐代文学家，后人称杜甫为“老杜”，称杜牧为“小杜”。《阿(ē)房宫赋》亦颇有名。杰出的诗人、散文家，是宰相杜佑之孙...</span></div>
</div>

<!-- end of 5 block -->
<div style="float:left;margin-bottom:20px;padding:10px;border-bottom:dotted 1px grey;">
<div><span>藏书之家</span></div>
<div><span>杜牧（公元803－约853年），字牧之，号“樊川居士”，号称杜紫薇。京兆万年（今陕西西安）人，晚唐诗人。（来源：中书省别名紫微省，因此人称其为“杜紫薇” ）晚唐时期.唐代文学家，后人称杜甫为“老杜”，称杜牧为“小杜”。《阿(ē)房宫赋》亦颇有名。杰出的诗人、散文家，是宰相杜佑之孙...</span></div>
</div>

<!-- end of 6 block -->
<div style="float:left;margin-bottom:20px;padding:10px;border-bottom:dotted 1px grey;">
<div><span>生平</span></div>
<div><span>杜牧（公元803－约853年），字牧之，号“樊川居士”，号称杜紫薇。京兆万年（今陕西西安）人，晚唐诗人。（来源：中书省别名紫微省，因此人称其为“杜紫薇” ）晚唐时期.唐代文学家，后人称杜甫为“老杜”，称杜牧为“小杜”。《阿(ē)房宫赋》亦颇有名。杰出的诗人、散文家，是宰相杜佑之孙...</span></div>
</div>

<!-- end of 7 block -->
</div>

</div>
</div>
</div>